"""
notifier.py — delivers scored job results via Gmail (HTML digest) and/or Notion.
"""

import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# ── Gmail ──────────────────────────────────────────────────────────────────────

SCORE_COLOR = {
    "excellent": "#16a34a",   # green  85+
    "good":      "#2563eb",   # blue   70–84
    "decent":    "#d97706",   # amber  55–69
}

def _score_label(score: int) -> tuple[str, str]:
    if score >= 85:
        return "Excellent", SCORE_COLOR["excellent"]
    if score >= 70:
        return "Good", SCORE_COLOR["good"]
    return "Decent", SCORE_COLOR["decent"]


def _build_html(jobs: list[dict]) -> str:
    today = date.today().strftime("%d %b %Y")
    rows = ""
    for j in jobs:
        label, color = _score_label(j["score"])
        rows += f"""
        <tr>
          <td style="padding:10px 8px;border-bottom:1px solid #e5e7eb;">
            <a href="{j['url']}" style="font-weight:600;color:#111827;text-decoration:none;font-size:14px;">
              {j['title']}
            </a><br>
            <span style="color:#6b7280;font-size:13px;">{j['company']} · {j['location']}</span><br>
            <span style="color:#6b7280;font-size:12px;font-style:italic;">{j.get('reason','')}</span>
          </td>
          <td style="padding:10px 8px;border-bottom:1px solid #e5e7eb;text-align:center;white-space:nowrap;">
            <span style="background:{color};color:#fff;padding:3px 10px;border-radius:12px;font-size:13px;font-weight:600;">
              {j['score']} — {label}
            </span><br>
            <span style="color:#9ca3af;font-size:11px;">{j['source']}</span>
          </td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:20px;">
  <div style="max-width:720px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;
              box-shadow:0 1px 3px rgba(0,0,0,.1);">

    <div style="background:#1e3a5f;padding:24px 28px;">
      <h1 style="color:#fff;margin:0;font-size:20px;">🎯 Daily Job Digest — {today}</h1>
      <p style="color:#93c5fd;margin:6px 0 0;font-size:14px;">
        {len(jobs)} new matches · sorted by fit score
      </p>
    </div>

    <div style="padding:20px 28px;">
      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:#f3f4f6;">
            <th style="padding:8px;text-align:left;font-size:12px;color:#6b7280;text-transform:uppercase;">Role</th>
            <th style="padding:8px;text-align:center;font-size:12px;color:#6b7280;text-transform:uppercase;width:150px;">Score</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
    </div>

    <div style="padding:16px 28px;background:#f9fafb;border-top:1px solid #e5e7eb;">
      <p style="color:#9ca3af;font-size:12px;margin:0;">
        Auto-generated by your job hunter · <a href="https://github.com" style="color:#9ca3af;">View repo</a>
      </p>
    </div>
  </div>
</body>
</html>"""


def send_email(jobs: list[dict]) -> None:
    gmail_user = os.environ.get("GMAIL_USER")
    gmail_pass = os.environ.get("GMAIL_APP_PASSWORD")
    gmail_to   = os.environ.get("GMAIL_TO", gmail_user)

    if not gmail_user or not gmail_pass:
        print("  [Email] GMAIL_USER or GMAIL_APP_PASSWORD not set, skipping.")
        return

    today = date.today().strftime("%d %b %Y")
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🎯 {len(jobs)} new job matches — {today}"
    msg["From"]    = gmail_user
    msg["To"]      = gmail_to

    html = _build_html(jobs)
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_user, gmail_pass)
            server.sendmail(gmail_user, gmail_to, msg.as_string())
        print(f"  [Email] Sent digest with {len(jobs)} jobs to {gmail_to}")
    except Exception as e:
        print(f"  [Email] Failed: {e}")


# ── Notion ─────────────────────────────────────────────────────────────────────

def add_to_notion(jobs: list[dict]) -> None:
    notion_token = os.environ.get("NOTION_TOKEN")
    database_id  = os.environ.get("NOTION_DATABASE_ID")

    if not notion_token or not database_id:
        print("  [Notion] NOTION_TOKEN or NOTION_DATABASE_ID not set, skipping.")
        return

    try:
        from notion_client import Client  # type: ignore
        notion = Client(auth=notion_token)

        for j in jobs:
            label, _ = _score_label(j["score"])
            try:
                notion.pages.create(
                    parent={"database_id": database_id},
                    properties={
                        "Title": {
                            "title": [{"text": {"content": j["title"]}}]
                        },
                        "Company": {
                            "rich_text": [{"text": {"content": j["company"]}}]
                        },
                        "Location": {
                            "rich_text": [{"text": {"content": j["location"]}}]
                        },
                        "Score": {
                            "number": j["score"]
                        },
                        "Label": {
                            "select": {"name": label}
                        },
                        "Source": {
                            "select": {"name": j["source"]}
                        },
                        "URL": {
                            "url": j["url"] or None
                        },
                        "Reason": {
                            "rich_text": [{"text": {"content": j.get("reason", "")}}]
                        },
                        "Status": {
                            "select": {"name": "New"}
                        },
                        "Date": {
                            "date": {"start": date.today().isoformat()}
                        },
                    },
                )
            except Exception as e:
                print(f"  [Notion] Could not add '{j['title']}': {e}")

        print(f"  [Notion] Added {len(jobs)} jobs to database")
    except ImportError:
        print("  [Notion] notion-client not installed, skipping.")
    except Exception as e:
        print(f"  [Notion] Failed: {e}")
